name: Publish Plugin for Kibana

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build plugin for publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kibana repo
        uses: actions/checkout@v3
        with:
          repository: elastic/kibana
          ref: 8.6 # Change this to a variable for each new version

      - name: Checkout Git repository
        uses: actions/checkout@v3
        with:
          path: plugins/mitre_attack

      - name: Enable node version
        uses: actions/setup-node@v3
        with:
          node-version: 16.19.1

      - name: Install dependencies
        working-directory: plugins/mitre_attack/
        run: yarn kbn bootstrap

      - name: Install dependencies
        working-directory: plugins/mitre_attack/ 
        run: yarn plugin-helpers build --kibana-version 8.6 # Change this to a variable for each new version
      
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "First release"
          files: |
            plugins/mitre_attack/build/mitreAttack-8.6.zip 

